version: "3"

vars:
  LOCAL_BIN: "{{.TASKFILE_DIR}}/bin"

tasks:
  install-deps:
    desc: "Install binary dependencies"
    cmds:
      - mkdir -p {{.LOCAL_BIN}}
      - GOBIN={{.LOCAL_BIN}} go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1 # protofiles
      - GOBIN={{.LOCAL_BIN}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2 # protofiles

  generate:whiteboard:
    desc: "Generate code from whiteboard proto files"
    cmds:
      - >
        protoc -I proto proto/whiteboard/*.proto
        --go_out=./gen/go/
        --go_opt=paths=source_relative
        --go-grpc_out=./gen/go/
        --go-grpc_opt=paths=source_relative
